[profile.dev.package."*"]
opt-level = 3

[workspace]
resolver = "2"

members = [
    "template_game", 
    "template_lib", 
    "template_macros", 
    "tools/ci"
]

default-members = ["template_game","template_lib"]
