[package]
name = "ci"
version = "0.1.0"
edition = "2021"
description = "CI script for TEMPLATE"
publish = false
license = "MIT OR Apache 2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
xshell = "0.2"
bitflags = "1.3"